[package]
name = "esercitazione-funzioni-varie-op"
version = "0.1.0"
authors = ["DarkCh4osss <67869598+DarkCh4osss@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
